/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/maintenance/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger retention cleanup (runs + audio cache)
         * @description Runs best-effort retention cleanup based on environment configuration.
         *     Notes:
         *     - Never deletes transcripts under `output/<channelDir>/...`.
         *     - Deletes only API run persistence under `output/_runs/*` (if enabled) and old audio cache files under `audio/*`.
         */
        post: operations["triggerMaintenanceCleanup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List watchlist entries */
        get: operations["listWatchlist"];
        put?: never;
        /** Add watchlist entry */
        post: operations["addWatchlistEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get watchlist entry */
        get: operations["getWatchlistEntry"];
        put?: never;
        post?: never;
        /** Remove watchlist entry */
        delete: operations["removeWatchlistEntry"];
        options?: never;
        head?: never;
        /** Update watchlist entry */
        patch: operations["updateWatchlistEntry"];
        trace?: never;
    };
    "/scheduler/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get scheduler status */
        get: operations["getSchedulerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduler/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start scheduler loop (in-process) */
        post: operations["startScheduler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduler/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop scheduler loop (in-process) */
        post: operations["stopScheduler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduler/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger one scheduler check cycle */
        post: operations["triggerSchedulerOnce"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream global events (SSE)
         * @description Server-Sent Events stream for global run updates. Event names include:
         *     - run:created
         *     - run:updated
         *     Data is JSON matching the GlobalRunEvent schema.
         */
        get: operations["streamGlobalEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs */
        get: operations["listRuns"];
        put?: never;
        /**
         * Create and start a run
         * @description Starts a run. For single-video URLs, the API is cache-first:
         *     if outputs already exist and `force` is false, the API returns a `done` run immediately (no transcription).
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan a run (enumerate + skip counts, no transcription)
         * @description Enumerates the input URL and computes how many videos are already processed vs remaining,
         *     without downloading audio or calling the transcription provider.
         */
        post: operations["planRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request cancellation of a run
         * @description Cooperative cancellation. If the run is running, the pipeline stops starting new work and ends as soon as practical.
         *     In-flight video work may finish. Queued runs are cancelled immediately.
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artifacts for a run (channel videos listing) */
        get: operations["getRunArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream run events (SSE)
         * @description Server-Sent Events stream. Event names include:
         *     - run:start, run:done, run:cancelled, run:error
         *     - video:start, video:stage, video:done, video:skip, video:error
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List channels from output directory */
        get: operations["listLibraryChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels/{channelDirName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get channel metadata */
        get: operations["getLibraryChannelMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels/{channelDirName}/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List videos for a channel */
        get: operations["listLibraryVideos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels/{channelDirName}/videos/{basename}/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a specific video artifact */
        get: operations["getLibraryVideoArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            message?: string;
        };
        OkResponse: {
            ok: boolean;
        };
        CleanupResponse: {
            retention: {
                nowIso: string;
                runs: {
                    enabled: boolean;
                    days: number;
                    deleted: number;
                    kept: number;
                    errors: number;
                };
                audio: {
                    enabled: boolean;
                    days: number;
                    deletedFiles: number;
                    keptFiles: number;
                    errors: number;
                };
            };
        };
        WatchlistEntry: {
            id: string;
            channelUrl: string;
            channelId?: string;
            channelTitle?: string;
            intervalMinutes?: number;
            enabled: boolean;
            lastCheckedAt?: string;
            lastRunId?: string;
            createdAt: string;
        };
        WatchlistCreateRequest: {
            /** @description YouTube channel or playlist URL (watchlist is for recurring sources, not single videos). */
            channelUrl: string;
            intervalMinutes?: number;
            enabled?: boolean;
        };
        WatchlistUpdateRequest: {
            intervalMinutes?: number;
            enabled?: boolean;
        };
        WatchlistEntryResponse: {
            entry: components["schemas"]["WatchlistEntry"];
        };
        WatchlistListResponse: {
            entries: components["schemas"]["WatchlistEntry"][];
        };
        SchedulerStatus: {
            enabled: boolean;
            running: boolean;
            intervalMinutes: number;
            maxConcurrentRuns: number;
            lastTickAt?: string;
            nextTickAt?: string;
        };
        SchedulerStatusResponse: {
            status: components["schemas"]["SchedulerStatus"];
        };
        SchedulerTriggerResponse: {
            result: {
                checked: number;
                runsCreated: number;
            };
            status: components["schemas"]["SchedulerStatus"];
        };
        HealthResponse: {
            ok: boolean;
            service: string;
            version?: string;
            deps?: {
                ytDlp?: {
                    ok: boolean;
                    version?: string;
                    error?: string;
                };
                ffmpeg?: {
                    ok: boolean;
                    error?: string;
                };
                disk?: {
                    ok: boolean;
                    freeBytes?: number;
                    freeGb?: number;
                    error?: string;
                };
                persist?: {
                    ok: boolean;
                    dir: string;
                    writable: boolean;
                    error?: string;
                };
            };
        };
        /** @enum {string} */
        RunStatus: "queued" | "running" | "done" | "error" | "cancelled";
        RunStats: {
            succeeded: number;
            failed: number;
            skipped: number;
            total: number;
        };
        RunRecord: {
            /** Format: uuid */
            runId: string;
            status: components["schemas"]["RunStatus"];
            inputUrl: string;
            force: boolean;
            createdAt: string;
            startedAt?: string;
            finishedAt?: string;
            cancelRequested?: boolean;
            error?: string;
            callbackUrl?: string;
            channelId?: string;
            channelTitle?: string;
            channelDirName?: string;
            previewVideoId?: string;
            previewTitle?: string;
            stats?: components["schemas"]["RunStats"];
        };
        RunsResponse: {
            runs: components["schemas"]["RunRecord"][];
        };
        RunGetResponse: {
            run: components["schemas"]["RunRecord"];
        };
        RunCreateRequest: {
            url: string;
            force?: boolean;
            /**
             * @description Optional. If set, the API sends a POST webhook when the run ends:
             *     - `run:done` when status becomes done
             *     - `run:error` when status becomes error
             *     - `run:cancelled` when status becomes cancelled
             *     If `Y2T_WEBHOOK_SECRET` is set on the server, requests include:
             *     - `X-Y2T-Timestamp` (ISO)
             *     - `X-Y2T-Signature` (HMAC-SHA256 of `${timestamp}.${body}`)
             */
            callbackUrl?: string;
            config?: {
                [key: string]: unknown;
            };
        };
        RunCreateLinks: {
            run: string;
            events: string;
            artifacts: string;
            cancel: string;
        };
        RunCreateResponse: {
            run: components["schemas"]["RunRecord"];
            links: components["schemas"]["RunCreateLinks"];
        };
        PlannedVideo: {
            id: string;
            title: string;
            url: string;
            uploadDate?: string;
            basename: string;
            processed: boolean;
        };
        RunPlan: {
            inputUrl: string;
            force: boolean;
            channelId: string;
            channelTitle?: string;
            totalVideos: number;
            alreadyProcessed: number;
            toProcess: number;
            filters: {
                afterDate?: string;
                maxVideos?: number;
            };
            videos: components["schemas"]["PlannedVideo"][];
        };
        RunPlanResponse: {
            plan: components["schemas"]["RunPlan"];
        };
        ChannelInfo: {
            channelId: string;
            channelTitle?: string;
            channelDirName: string;
            channelThumbnailUrl?: string;
            metaPath?: string;
        };
        ChannelsResponse: {
            channels: components["schemas"]["ChannelInfo"][];
        };
        ChannelMeta: {
            channelId: string;
            channelTitle: string;
            channelUrl: string;
            retrievedAt?: string;
        };
        ChannelMetaResponse: {
            channelDirName: string;
            meta: components["schemas"]["ChannelMeta"];
        };
        OutputPaths: {
            jsonPath: string;
            txtPath: string;
            mdPath: string;
            jsonlPath: string;
            csvPath: string;
            commentsPath: string;
            metaPath: string;
            channelMetaPath: string;
            errorLogPath: string;
            audioPath: string;
        };
        VideoMeta: {
            videoId: string;
            title?: string;
            channelId?: string;
            channelTitle?: string;
            channelUrl?: string;
            videoUrl?: string;
            description?: string;
            publishedAt?: string;
            languageCode?: string;
            languageDetection?: string;
            languageConfidence?: number;
        };
        VideoInfo: {
            videoId: string;
            title?: string;
            basename: string;
            metaPath?: string;
            paths: components["schemas"]["OutputPaths"];
            meta?: components["schemas"]["VideoMeta"];
        };
        VideosResponse: {
            channelDirName: string;
            videos: components["schemas"]["VideoInfo"][];
        };
        /** @enum {string} */
        ArtifactKind: "txt" | "md" | "json" | "jsonl" | "meta" | "comments" | "csv" | "audio";
        RunArtifacts: {
            channelDirName?: string;
            channelId?: string;
            channelTitle?: string;
            videos: components["schemas"]["VideoInfo"][];
        };
        RunArtifactsResponse: {
            run: components["schemas"]["RunRecord"];
            artifacts: components["schemas"]["RunArtifacts"];
        };
        /** @enum {string} */
        GlobalRunEventType: "run:created" | "run:updated";
        GlobalRunEvent: {
            type: components["schemas"]["GlobalRunEventType"];
            run: components["schemas"]["RunRecord"];
            timestamp: string;
        };
    };
    responses: never;
    parameters: {
        RunId: string;
        ChannelDirName: string;
        Basename: string;
        ArtifactKind: components["schemas"]["ArtifactKind"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    triggerMaintenanceCleanup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistListResponse"];
                };
            };
        };
    };
    addWatchlistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistEntryResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getWatchlistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistEntryResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeWatchlistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateWatchlistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistEntryResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSchedulerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusResponse"];
                };
            };
        };
    };
    startScheduler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusResponse"];
                };
            };
        };
    };
    stopScheduler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusResponse"];
                };
            };
        };
    };
    triggerSchedulerOnce: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerTriggerResponse"];
                };
            };
        };
    };
    streamGlobalEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: {
                /** @description When true, returns a best-effort deep health check (deps + disk + persistence). */
                deep?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    planRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPlanResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunGetResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunGetResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRunArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunArtifactsResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    listLibraryChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelsResponse"];
                };
            };
        };
    };
    getLibraryChannelMeta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelDirName: components["parameters"]["ChannelDirName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelMetaResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLibraryVideos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelDirName: components["parameters"]["ChannelDirName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideosResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLibraryVideoArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelDirName: components["parameters"]["ChannelDirName"];
                basename: components["parameters"]["Basename"];
                kind: components["parameters"]["ArtifactKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
