/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream global events (SSE)
         * @description Server-Sent Events stream for global run updates. Event names include:
         *     - run:created
         *     - run:updated
         *     Data is JSON matching the GlobalRunEvent schema.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunsResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create and start a run
         * @description Starts a run. For single-video URLs, the API is cache-first:
         *     if outputs already exist and `force` is false, the API returns a `done` run immediately (no transcription).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RunCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunCreateResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan a run (enumerate + skip counts, no transcription)
         * @description Enumerates the input URL and computes how many videos are already processed vs remaining,
         *     without downloading audio or calling the transcription provider.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RunCreateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunPlanResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunGetResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artifacts for a run (channel videos listing) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunArtifactsResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream run events (SSE)
         * @description Server-Sent Events stream. Event names include:
         *     - run:start, run:done, run:error
         *     - video:start, video:stage, video:done, video:skip, video:error
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List channels from output directory */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels/{channelDirName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get channel metadata */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channelDirName: components["parameters"]["ChannelDirName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelMetaResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels/{channelDirName}/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List videos for a channel */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channelDirName: components["parameters"]["ChannelDirName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideosResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels/{channelDirName}/videos/{basename}/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a specific video artifact */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channelDirName: components["parameters"]["ChannelDirName"];
                    basename: components["parameters"]["Basename"];
                    kind: components["parameters"]["ArtifactKind"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            message?: string;
        };
        HealthResponse: {
            ok: boolean;
            service: string;
        };
        /** @enum {string} */
        RunStatus: "queued" | "running" | "done" | "error";
        RunStats: {
            succeeded: number;
            failed: number;
            skipped: number;
            total: number;
        };
        RunRecord: {
            /** Format: uuid */
            runId: string;
            status: components["schemas"]["RunStatus"];
            inputUrl: string;
            force: boolean;
            createdAt: string;
            startedAt?: string;
            finishedAt?: string;
            error?: string;
            callbackUrl?: string;
            channelId?: string;
            channelTitle?: string;
            channelDirName?: string;
            previewVideoId?: string;
            previewTitle?: string;
            stats?: components["schemas"]["RunStats"];
        };
        RunsResponse: {
            runs: components["schemas"]["RunRecord"][];
        };
        RunGetResponse: {
            run: components["schemas"]["RunRecord"];
        };
        RunCreateRequest: {
            url: string;
            force?: boolean;
            /**
             * @description Optional. If set, the API sends a POST webhook when the run ends:
             *     - `run:done` when status becomes done
             *     - `run:error` when status becomes error
             *     If `Y2T_WEBHOOK_SECRET` is set on the server, requests include:
             *     - `X-Y2T-Timestamp` (ISO)
             *     - `X-Y2T-Signature` (HMAC-SHA256 of `${timestamp}.${body}`)
             */
            callbackUrl?: string;
            config?: {
                [key: string]: unknown;
            };
        };
        RunCreateLinks: {
            run: string;
            events: string;
            artifacts: string;
        };
        RunCreateResponse: {
            run: components["schemas"]["RunRecord"];
            links: components["schemas"]["RunCreateLinks"];
        };
        PlannedVideo: {
            id: string;
            title: string;
            url: string;
            uploadDate?: string;
            basename: string;
            processed: boolean;
        };
        RunPlan: {
            inputUrl: string;
            force: boolean;
            channelId: string;
            channelTitle?: string;
            totalVideos: number;
            alreadyProcessed: number;
            toProcess: number;
            filters: {
                afterDate?: string;
                maxVideos?: number;
            };
            videos: components["schemas"]["PlannedVideo"][];
        };
        RunPlanResponse: {
            plan: components["schemas"]["RunPlan"];
        };
        ChannelInfo: {
            channelId: string;
            channelTitle?: string;
            channelDirName: string;
            channelThumbnailUrl?: string;
            metaPath?: string;
        };
        ChannelsResponse: {
            channels: components["schemas"]["ChannelInfo"][];
        };
        ChannelMeta: {
            channelId: string;
            channelTitle: string;
            channelUrl: string;
            retrievedAt?: string;
        };
        ChannelMetaResponse: {
            channelDirName: string;
            meta: components["schemas"]["ChannelMeta"];
        };
        OutputPaths: {
            jsonPath: string;
            txtPath: string;
            mdPath: string;
            jsonlPath: string;
            csvPath: string;
            commentsPath: string;
            metaPath: string;
            channelMetaPath: string;
            errorLogPath: string;
            audioPath: string;
        };
        VideoMeta: {
            videoId: string;
            title?: string;
            channelId?: string;
            channelTitle?: string;
            channelUrl?: string;
            videoUrl?: string;
            description?: string;
            publishedAt?: string;
            languageCode?: string;
            languageDetection?: string;
            languageConfidence?: number;
        };
        VideoInfo: {
            videoId: string;
            title?: string;
            basename: string;
            metaPath?: string;
            paths: components["schemas"]["OutputPaths"];
            meta?: components["schemas"]["VideoMeta"];
        };
        VideosResponse: {
            channelDirName: string;
            videos: components["schemas"]["VideoInfo"][];
        };
        /** @enum {string} */
        ArtifactKind: "txt" | "md" | "json" | "jsonl" | "meta" | "comments" | "csv" | "audio";
        RunArtifacts: {
            channelDirName?: string;
            channelId?: string;
            channelTitle?: string;
            videos: components["schemas"]["VideoInfo"][];
        };
        RunArtifactsResponse: {
            run: components["schemas"]["RunRecord"];
            artifacts: components["schemas"]["RunArtifacts"];
        };
        /** @enum {string} */
        GlobalRunEventType: "run:created" | "run:updated";
        GlobalRunEvent: {
            type: components["schemas"]["GlobalRunEventType"];
            run: components["schemas"]["RunRecord"];
            timestamp: string;
        };
    };
    responses: never;
    parameters: {
        RunId: string;
        ChannelDirName: string;
        Basename: string;
        ArtifactKind: components["schemas"]["ArtifactKind"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
